### PR TITLE
Port to ros2

### PR DESCRIPTION
**Pull request by vatanaksoytezer**

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
The CI will fail since it is for ROS1. If we want to release this I can add rolling, galactic and foxy CI's along within this PR

**Comment by henningkayser** [comment]
> The CI will fail since it is for ROS1. If we want to release this I can add rolling, galactic and foxy CI's along within this PR

I think we should fix CI before merging. Could you do this?

**Comment by vatanaksoytezer** [comment]
> > The CI will fail since it is for ROS1. If we want to release this I can add rolling, galactic and foxy CI's along within this PR
> 
> I think we should fix CI before merging. Could you do this?

Sure, totally.

**Comment by vatanaksoytezer** [comment]
@henningkayser I've added GHA for ROS2. Can you enable them for this repo?

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
